# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datatype.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='datatype.proto',
  package='datatype',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x64\x61tatype.proto\x12\x08\x64\x61tatype\"%\n\rStringMessage\x12\x14\n\x0cstring_field\x18\x01 \x01(\t\"#\n\x0c\x42ytesMessage\x12\x13\n\x0b\x62ytes_field\x18\x01 \x01(\x0c\"!\n\x0b\x42oolMessage\x12\x12\n\nbool_field\x18\x01 \x01(\x08\"\x1f\n\nIntMessage\x12\x11\n\tint_field\x18\x01 \x01(\x05\"#\n\x0c\x46loatMessage\x12\x13\n\x0b\x66loat_field\x18\x01 \x01(\x02\"#\n\x0eListIntMessage\x12\x11\n\tint_field\x18\x01 \x03(\x05\")\n\x11ListStringMessage\x12\x14\n\x0cstring_field\x18\x01 \x03(\t\"\x7f\n\x0e\x44ictMessagei2s\x12;\n\ndict_field\x18\x01 \x03(\x0b\x32\'.datatype.DictMessagei2s.DictFieldEntry\x1a\x30\n\x0e\x44ictFieldEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x7f\n\x0e\x44ictMessages2s\x12;\n\ndict_field\x18\x01 \x03(\x0b\x32\'.datatype.DictMessages2s.DictFieldEntry\x1a\x30\n\x0e\x44ictFieldEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')
)




_STRINGMESSAGE = _descriptor.Descriptor(
  name='StringMessage',
  full_name='datatype.StringMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='string_field', full_name='datatype.StringMessage.string_field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=65,
)


_BYTESMESSAGE = _descriptor.Descriptor(
  name='BytesMessage',
  full_name='datatype.BytesMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bytes_field', full_name='datatype.BytesMessage.bytes_field', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=102,
)


_BOOLMESSAGE = _descriptor.Descriptor(
  name='BoolMessage',
  full_name='datatype.BoolMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bool_field', full_name='datatype.BoolMessage.bool_field', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=137,
)


_INTMESSAGE = _descriptor.Descriptor(
  name='IntMessage',
  full_name='datatype.IntMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='int_field', full_name='datatype.IntMessage.int_field', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=170,
)


_FLOATMESSAGE = _descriptor.Descriptor(
  name='FloatMessage',
  full_name='datatype.FloatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='float_field', full_name='datatype.FloatMessage.float_field', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=207,
)


_LISTINTMESSAGE = _descriptor.Descriptor(
  name='ListIntMessage',
  full_name='datatype.ListIntMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='int_field', full_name='datatype.ListIntMessage.int_field', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=244,
)


_LISTSTRINGMESSAGE = _descriptor.Descriptor(
  name='ListStringMessage',
  full_name='datatype.ListStringMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='string_field', full_name='datatype.ListStringMessage.string_field', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=287,
)


_DICTMESSAGEI2S_DICTFIELDENTRY = _descriptor.Descriptor(
  name='DictFieldEntry',
  full_name='datatype.DictMessagei2s.DictFieldEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='datatype.DictMessagei2s.DictFieldEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='datatype.DictMessagei2s.DictFieldEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=416,
)

_DICTMESSAGEI2S = _descriptor.Descriptor(
  name='DictMessagei2s',
  full_name='datatype.DictMessagei2s',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dict_field', full_name='datatype.DictMessagei2s.dict_field', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DICTMESSAGEI2S_DICTFIELDENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=416,
)


_DICTMESSAGES2S_DICTFIELDENTRY = _descriptor.Descriptor(
  name='DictFieldEntry',
  full_name='datatype.DictMessages2s.DictFieldEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='datatype.DictMessages2s.DictFieldEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='datatype.DictMessages2s.DictFieldEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=545,
)

_DICTMESSAGES2S = _descriptor.Descriptor(
  name='DictMessages2s',
  full_name='datatype.DictMessages2s',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dict_field', full_name='datatype.DictMessages2s.dict_field', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DICTMESSAGES2S_DICTFIELDENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=545,
)

_DICTMESSAGEI2S_DICTFIELDENTRY.containing_type = _DICTMESSAGEI2S
_DICTMESSAGEI2S.fields_by_name['dict_field'].message_type = _DICTMESSAGEI2S_DICTFIELDENTRY
_DICTMESSAGES2S_DICTFIELDENTRY.containing_type = _DICTMESSAGES2S
_DICTMESSAGES2S.fields_by_name['dict_field'].message_type = _DICTMESSAGES2S_DICTFIELDENTRY
DESCRIPTOR.message_types_by_name['StringMessage'] = _STRINGMESSAGE
DESCRIPTOR.message_types_by_name['BytesMessage'] = _BYTESMESSAGE
DESCRIPTOR.message_types_by_name['BoolMessage'] = _BOOLMESSAGE
DESCRIPTOR.message_types_by_name['IntMessage'] = _INTMESSAGE
DESCRIPTOR.message_types_by_name['FloatMessage'] = _FLOATMESSAGE
DESCRIPTOR.message_types_by_name['ListIntMessage'] = _LISTINTMESSAGE
DESCRIPTOR.message_types_by_name['ListStringMessage'] = _LISTSTRINGMESSAGE
DESCRIPTOR.message_types_by_name['DictMessagei2s'] = _DICTMESSAGEI2S
DESCRIPTOR.message_types_by_name['DictMessages2s'] = _DICTMESSAGES2S
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StringMessage = _reflection.GeneratedProtocolMessageType('StringMessage', (_message.Message,), dict(
  DESCRIPTOR = _STRINGMESSAGE,
  __module__ = 'datatype_pb2'
  # @@protoc_insertion_point(class_scope:datatype.StringMessage)
  ))
_sym_db.RegisterMessage(StringMessage)

BytesMessage = _reflection.GeneratedProtocolMessageType('BytesMessage', (_message.Message,), dict(
  DESCRIPTOR = _BYTESMESSAGE,
  __module__ = 'datatype_pb2'
  # @@protoc_insertion_point(class_scope:datatype.BytesMessage)
  ))
_sym_db.RegisterMessage(BytesMessage)

BoolMessage = _reflection.GeneratedProtocolMessageType('BoolMessage', (_message.Message,), dict(
  DESCRIPTOR = _BOOLMESSAGE,
  __module__ = 'datatype_pb2'
  # @@protoc_insertion_point(class_scope:datatype.BoolMessage)
  ))
_sym_db.RegisterMessage(BoolMessage)

IntMessage = _reflection.GeneratedProtocolMessageType('IntMessage', (_message.Message,), dict(
  DESCRIPTOR = _INTMESSAGE,
  __module__ = 'datatype_pb2'
  # @@protoc_insertion_point(class_scope:datatype.IntMessage)
  ))
_sym_db.RegisterMessage(IntMessage)

FloatMessage = _reflection.GeneratedProtocolMessageType('FloatMessage', (_message.Message,), dict(
  DESCRIPTOR = _FLOATMESSAGE,
  __module__ = 'datatype_pb2'
  # @@protoc_insertion_point(class_scope:datatype.FloatMessage)
  ))
_sym_db.RegisterMessage(FloatMessage)

ListIntMessage = _reflection.GeneratedProtocolMessageType('ListIntMessage', (_message.Message,), dict(
  DESCRIPTOR = _LISTINTMESSAGE,
  __module__ = 'datatype_pb2'
  # @@protoc_insertion_point(class_scope:datatype.ListIntMessage)
  ))
_sym_db.RegisterMessage(ListIntMessage)

ListStringMessage = _reflection.GeneratedProtocolMessageType('ListStringMessage', (_message.Message,), dict(
  DESCRIPTOR = _LISTSTRINGMESSAGE,
  __module__ = 'datatype_pb2'
  # @@protoc_insertion_point(class_scope:datatype.ListStringMessage)
  ))
_sym_db.RegisterMessage(ListStringMessage)

DictMessagei2s = _reflection.GeneratedProtocolMessageType('DictMessagei2s', (_message.Message,), dict(

  DictFieldEntry = _reflection.GeneratedProtocolMessageType('DictFieldEntry', (_message.Message,), dict(
    DESCRIPTOR = _DICTMESSAGEI2S_DICTFIELDENTRY,
    __module__ = 'datatype_pb2'
    # @@protoc_insertion_point(class_scope:datatype.DictMessagei2s.DictFieldEntry)
    ))
  ,
  DESCRIPTOR = _DICTMESSAGEI2S,
  __module__ = 'datatype_pb2'
  # @@protoc_insertion_point(class_scope:datatype.DictMessagei2s)
  ))
_sym_db.RegisterMessage(DictMessagei2s)
_sym_db.RegisterMessage(DictMessagei2s.DictFieldEntry)

DictMessages2s = _reflection.GeneratedProtocolMessageType('DictMessages2s', (_message.Message,), dict(

  DictFieldEntry = _reflection.GeneratedProtocolMessageType('DictFieldEntry', (_message.Message,), dict(
    DESCRIPTOR = _DICTMESSAGES2S_DICTFIELDENTRY,
    __module__ = 'datatype_pb2'
    # @@protoc_insertion_point(class_scope:datatype.DictMessages2s.DictFieldEntry)
    ))
  ,
  DESCRIPTOR = _DICTMESSAGES2S,
  __module__ = 'datatype_pb2'
  # @@protoc_insertion_point(class_scope:datatype.DictMessages2s)
  ))
_sym_db.RegisterMessage(DictMessages2s)
_sym_db.RegisterMessage(DictMessages2s.DictFieldEntry)


_DICTMESSAGEI2S_DICTFIELDENTRY._options = None
_DICTMESSAGES2S_DICTFIELDENTRY._options = None
# @@protoc_insertion_point(module_scope)
