# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='auth.proto',
  package='Auth',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nauth.proto\x12\x04\x41uth\"\x16\n\x05Token\x12\r\n\x05token\x18\x01 \x01(\t\"C\n\x0bValidResult\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\x12\x11\n\tuser_name\x18\x03 \x01(\t27\n\nValidToken\x12)\n\x05valid\x12\x0b.Auth.Token\x1a\x11.Auth.ValidResult\"\x00\x62\x06proto3')
)




_TOKEN = _descriptor.Descriptor(
  name='Token',
  full_name='Auth.Token',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='Auth.Token.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=42,
)


_VALIDRESULT = _descriptor.Descriptor(
  name='ValidResult',
  full_name='Auth.ValidResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_valid', full_name='Auth.ValidResult.is_valid', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='Auth.ValidResult.user_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_name', full_name='Auth.ValidResult.user_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['Token'] = _TOKEN
DESCRIPTOR.message_types_by_name['ValidResult'] = _VALIDRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Token = _reflection.GeneratedProtocolMessageType('Token', (_message.Message,), dict(
  DESCRIPTOR = _TOKEN,
  __module__ = 'auth_pb2'
  # @@protoc_insertion_point(class_scope:Auth.Token)
  ))
_sym_db.RegisterMessage(Token)

ValidResult = _reflection.GeneratedProtocolMessageType('ValidResult', (_message.Message,), dict(
  DESCRIPTOR = _VALIDRESULT,
  __module__ = 'auth_pb2'
  # @@protoc_insertion_point(class_scope:Auth.ValidResult)
  ))
_sym_db.RegisterMessage(ValidResult)



_VALIDTOKEN = _descriptor.ServiceDescriptor(
  name='ValidToken',
  full_name='Auth.ValidToken',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=113,
  serialized_end=168,
  methods=[
  _descriptor.MethodDescriptor(
    name='valid',
    full_name='Auth.ValidToken.valid',
    index=0,
    containing_service=None,
    input_type=_TOKEN,
    output_type=_VALIDRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VALIDTOKEN)

DESCRIPTOR.services_by_name['ValidToken'] = _VALIDTOKEN

# @@protoc_insertion_point(module_scope)
