# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import auth_pb2 as auth__pb2


class ValidTokenStub(object):
  """service interface define.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.valid = channel.unary_unary(
        '/Auth.ValidToken/valid',
        request_serializer=auth__pb2.Token.SerializeToString,
        response_deserializer=auth__pb2.ValidResult.FromString,
        )


class ValidTokenServicer(object):
  """service interface define.
  """

  def valid(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ValidTokenServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'valid': grpc.unary_unary_rpc_method_handler(
          servicer.valid,
          request_deserializer=auth__pb2.Token.FromString,
          response_serializer=auth__pb2.ValidResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Auth.ValidToken', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
